/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenprogramacion;

import java.awt.CheckboxGroup;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author alvar
 */
public class Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
        
            choice.addItem("º Kelvin");
            choice.addItem("º Farenheit");
            choice.addItem("º Celsius");
        
    }
    public void seleccion(){
        if(checkbox1.getState()== true){
            textof.setText("º C");
        }
        if(checkbox2.getState()==true){
            textof.setText("º F");
        }
        if(checkbox3.getState()==true){
            textof.setText("º K");
        }
        if("º Kelvin".equals(choice.getSelectedItem())){
            textok.setText("º K");
        }
        if("º Celsius".equals(choice.getSelectedItem())){
            textok.setText("º C");
        }
        if("º Farenheit".equals(choice.getSelectedItem())){
            textok.setText("º F");
        }
        
    }
    
    public void celsiusfarenheit(){
    F=(((Double.parseDouble(areaf.getText()))-32)*(5/9));
    areak.setText(F+"");
    
    
}
    public void celsiuskelvin(){
     K=((Double.parseDouble(areaf.getText()))-273.15);
    areak.setText(K+"");
    
    
}
    
    public void farenheitkelvin(){
     K=((Double.parseDouble(areaf.getText()))*(9/5)-241.15);
    areak.setText(K+"");
    
    
}
    public void farenheitcelsius(){
    C=((Double.parseDouble(areaf.getText()))*(9/5)+32);
    areak.setText(C+"");
}
    public void kelvincelsius(){
    C=((Double.parseDouble(areaf.getText()))+273.12);
    areak.setText(C+"");
}
    public void kelvinfarenheit(){
    F=((Double.parseDouble(areaf.getText())+241.15)*(5/9));
    System.out.print(F);
    areak.setText(F+"");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        aceptar = new java.awt.Button();
        areaf = new java.awt.TextField();
        areak = new java.awt.TextField();
        textok = new java.awt.Label();
        textof = new java.awt.Label();
        panel1 = new javax.swing.JPanel();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        panel2 = new javax.swing.JPanel();
        choice = new java.awt.Choice();
        realizar = new java.awt.Button();
        limpiar = new java.awt.Button();
        salir = new java.awt.Button();

        dialogo.setMinimumSize(new java.awt.Dimension(600, 600));
        dialogo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("ERROR EN LA INTRODUCCION DE TEXTO");
        dialogo.getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 40));

        aceptar.setLabel("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        dialogo.getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de temperaturas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(areaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, -1));

        areak.setEditable(false);
        getContentPane().add(areak, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, -1));

        textok.setText("º K");
        getContentPane().add(textok, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        textof.setText("º F");
        getContentPane().add(textof, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Convierte a º Farenheit"));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkbox1.setCheckboxGroup(cbg);
        checkbox1.setLabel("º Celsius");
        checkbox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox1ItemStateChanged(evt);
            }
        });
        panel1.add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        checkbox2.setCheckboxGroup(cbg);
        checkbox2.setLabel("º Farenheit");
        checkbox2.setState(true);
        checkbox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox2ItemStateChanged(evt);
            }
        });
        panel1.add(checkbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        checkbox3.setCheckboxGroup(cbg);
        checkbox3.setLabel("º Kelvin");
        checkbox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox3ItemStateChanged(evt);
            }
        });
        panel1.add(checkbox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 120));

        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder("a º Kelvin"));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        choice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceItemStateChanged(evt);
            }
        });
        panel2.add(choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 130, 120));

        realizar.setLabel("Realizar");
        realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarActionPerformed(evt);
            }
        });
        getContentPane().add(realizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        limpiar.setLabel("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        salir.setLabel("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        areaf.setText(null);
        areak.setText(null);
       areaf.requestFocus();
        checkbox1.setState(true);
        choice.select(1);  
        seleccion();
        F=0;
        K=0;
        C=0;
    }//GEN-LAST:event_limpiarActionPerformed

    
    
    
    private void realizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarActionPerformed
        // TODO add your handling code here:
        try{
        if("º C".equals(textof.getText()) && "º F".equals(textok.getText())){
            celsiusfarenheit();
        }
        if("º C".equals(textof.getText()) && "º K".equals(textok.getText())){
            celsiuskelvin();
        }
        if("º F".equals(textof.getText()) && "º C".equals(textok.getText())){
            farenheitcelsius();
        }
        if("º F".equals(textof.getText()) && "º K".equals(textok.getText())){
            farenheitkelvin();
        }
        if("º K".equals(textof.getText()) && "º C".equals(textok.getText())){
            kelvincelsius();
        }
        if("º K".equals(textof.getText()) && "º F".equals(textok.getText())){
            kelvinfarenheit();
        }    }catch (NumberFormatException e){
            dialogo.show();
        }
    }//GEN-LAST:event_realizarActionPerformed

    private void checkbox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox1ItemStateChanged
        // TODO add your handling code here:
        textof.setText("º C");
        
        
    }//GEN-LAST:event_checkbox1ItemStateChanged

    private void checkbox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox2ItemStateChanged
        // TODO add your handling code here:
        textof.setText("º F");
        
        
        
    }//GEN-LAST:event_checkbox2ItemStateChanged

    
    
    private void checkbox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox3ItemStateChanged
        // TODO add your handling code here:
        textof.setText("º K");
    }//GEN-LAST:event_checkbox3ItemStateChanged

    private void choiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceItemStateChanged
        // TODO add your handling code here:
        
        if("º Kelvin".equals(choice.getSelectedItem())){
            textok.setText("º K");
        }
        if("º Celsius".equals(choice.getSelectedItem())){
            textok.setText("º C");
        }
        if("º Farenheit".equals(choice.getSelectedItem())){
            textok.setText("º F");
        }
        
    }//GEN-LAST:event_choiceItemStateChanged

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        dialogo.dispose();
        textof.requestFocus();
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }
 
    protected double F,C,K;
 protected CheckboxGroup cbg= new CheckboxGroup();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected java.awt.Button aceptar;
    protected java.awt.TextField areaf;
    protected java.awt.TextField areak;
    protected java.awt.Checkbox checkbox1;
    protected java.awt.Checkbox checkbox2;
    protected java.awt.Checkbox checkbox3;
    protected java.awt.Choice choice;
    protected javax.swing.JDialog dialogo;
    protected java.awt.Label label1;
    protected java.awt.Button limpiar;
    protected javax.swing.JPanel panel1;
    protected javax.swing.JPanel panel2;
    protected java.awt.Button realizar;
    protected java.awt.Button salir;
    protected java.awt.Label textof;
    protected java.awt.Label textok;
    // End of variables declaration//GEN-END:variables
}
