/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenprogramacion;

import java.awt.CheckboxGroup;

/**
 *
 * @author alvar
 */
public class Ejercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
    }

    
    
     public void ordenar(int v[]) {
        for (int i = 0; i < v.length; i++) {
            for (int j = 0; j < v.length - 1; j++) {
                if (v[j] > v[j + 1]) {
                    int num = v[j + 1];
                    v[j+ 1] = v[j];
                    v[j] = num;
                }
            }
        }
    }
    public void simular()
    {
         Bombo bombo=new Bombo(50);//Integer.parseInt(numerosimulaciones.getText()));        
        for (int i = 0; i < array.length; i++)
        {
            array[i] = bombo.sacaBola()+1;
        }
        ordenar(array);
        
            for (int j = 0; j < 6; j++) 
            {
                tabla2.setValueAt(array[cont++], 0, j);
            }
        
        cont = 0;
    }
    
    public void generar()
    {
        
        for(int i=1;i<=(Integer.parseInt(numerosimulaciones.getText()));i++){
            simular();
            for(int j=0; j<6;j++){
               if(tabla1.getValueAt(0,j).equals(tabla2.getValueAt(0,j))){
                  
                   favorable++;
               }
            }
        }
        favorables.setText(favorable+"");
        favorable=0;
    }
    
    protected int[] array=new int[6];
    protected int cont;
    protected int favorable=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo = new javax.swing.JDialog();
        label6 = new java.awt.Label();
        aceptar = new java.awt.Button();
        label1 = new java.awt.Label();
        numerosimulaciones = new java.awt.TextField();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        jPanel1 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        nuevo = new java.awt.Button();
        realizar = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        probabilidad = new java.awt.TextField();
        favorables = new java.awt.TextField();

        dialogo.setMinimumSize(new java.awt.Dimension(600, 600));
        dialogo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label6.setText("ERROR EN LA INTRODUCCION DE NUMEROS");
        dialogo.getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        aceptar.setLabel("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        dialogo.getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador Bonoloto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("Nº de simulaciones");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));
        getContentPane().add(numerosimulaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 190, -1));

        checkbox1.setCheckboxGroup(cbg);
        checkbox1.setLabel("Simular");
        getContentPane().add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        checkbox2.setCheckboxGroup(cbg);
        checkbox2.setLabel("generar");
        checkbox2.setState(true);
        getContentPane().add(checkbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Simulacion Bonoloto"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label4.setText("Nº seleccionados");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        label5.setText("Nº Obtenidos");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 210, 60));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(24),  new Integer(17),  new Integer(31),  new Integer(9),  new Integer(42),  new Integer(13)}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 730, 120));

        nuevo.setLabel("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        realizar.setLabel("Realizar");
        realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarActionPerformed(evt);
            }
        });
        getContentPane().add(realizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Frecuencia"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setText("Casos favorables");
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        label3.setText("Probabilidad (%)");
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        probabilidad.setEditable(false);
        jPanel2.add(probabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 90, -1));

        favorables.setEditable(false);
        jPanel2.add(favorables, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 670, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void realizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarActionPerformed
        // TODO add your handling code here:
        
        
        if (checkbox1.getState()==true){
            
            simular();
        }
        
        if(checkbox2.getState()==true){
           
           try{
            double n=Integer.parseInt(numerosimulaciones.getText());
            double n2=6;
            nprobabilidad=((n2/n)*100);
            probabilidad.setText(nprobabilidad+"");
            generar();
            }catch (NumberFormatException e){
                dialogo.show();
            }
            
        }
        
    }//GEN-LAST:event_realizarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        dialogo.dispose();
        numerosimulaciones.requestFocus();
    }//GEN-LAST:event_aceptarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        numerosimulaciones.setText("");
        favorables.setText("");
        probabilidad.setText("");
        for (int i=0;i<6;i++){
            tabla1.setValueAt(null, 0, i);
            tabla2.setValueAt(null, 0, i);
        }
        numerosimulaciones.requestFocus();
        
    }//GEN-LAST:event_nuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }
      private double nprobabilidad;
protected CheckboxGroup cbg= new CheckboxGroup();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected java.awt.Button aceptar;
    protected java.awt.Checkbox checkbox1;
    protected java.awt.Checkbox checkbox2;
    protected javax.swing.JDialog dialogo;
    protected java.awt.TextField favorables;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JScrollPane jScrollPane3;
    protected java.awt.Label label1;
    protected java.awt.Label label2;
    protected java.awt.Label label3;
    protected java.awt.Label label4;
    protected java.awt.Label label5;
    protected java.awt.Label label6;
    protected java.awt.Button nuevo;
    protected java.awt.TextField numerosimulaciones;
    protected java.awt.TextField probabilidad;
    protected java.awt.Button realizar;
    protected javax.swing.JTable tabla1;
    protected javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
