/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alvar
 */
public class Cadenas extends javax.swing.JFrame {
 String palabra,cadena;
 StringBuffer cadena1=new StringBuffer();
 StringBuffer cadena2=new StringBuffer();
    /**
     * Creates new form Cadenas
     */
    public Cadenas() {
        initComponents();
        this.cadena=cadena;
    }

    public void rotarCadena( int orientacion, int caracteres){
        palabra=area1.getText();
        cadena1.append(palabra);
        String cadenaaux;
        if(orientacion==1){
            for (int i=0;i<palabra.length() ;i++ )
		{
                    cadena2.append(cadena1);
                    cadena1.setCharAt(i+caracteres, palabra.charAt(i));
                    
                    System.out.print(cadena1+"   ");
                    
                    System.out.print(cadena2+"   ");
                }
            
        }else{
            
        }
        
        
    }
	public void encriptaCadena(int rotacion, int caracter)
	{
            cadena=area1.getText();
		int encriptador;
		String cadenafinal="";
                if(rotacion==1){
		for (int i=0;i<=cadena.length()-1 ;i++ )
		{
			
			cadenafinal=cadenafinal+cambiaCaracter(cadena.charAt(i),caracter);
		}
		cadena=cadenafinal;
                area2.setText(cadena);
                }else{
                    for (int i=cadena.length()-1;i>=0 ;i-- )
		{
			
			cadenafinal=cadenafinal+cambiaCaracter(cadena.charAt(i),caracter);
		}
		cadena=cadenafinal;
                area2.setText(cadena);
                }
	}


        
	public void desencriptaCadena(int rotacion,int caracter)
	{
            cadena=area2.getText();
		int desencriptador;
		String cadenafinal="";
                if(rotacion==1){
		for (int i=0;i<=cadena.length()-1 ;i++ )
		{
			desencriptador=(int)cadena.charAt(i)-caracter;
			cadenafinal=cadenafinal+(char)desencriptador;
		}
		cadena=cadenafinal;
                area2.setText(cadena);
                }else{
                    for (int i=cadena.length()-1;i>=0 ;i-- )
		{
			desencriptador=(int)cadena.charAt(i)-caracter;
			cadenafinal=cadenafinal+(char)desencriptador;
		}
		cadena=cadenafinal;
                area2.setText(cadena);
                }
                
	}

	public String getCadena()
	{
		return cadena;
	}
    
    
        public char cambiaCaracter(char caracter, int ascii){
            char caractercambiado=' ';
            
            int cambio= (int) caracter+ascii;
            
            caractercambiado=(char)cambio;

            System.out.println(caractercambiado);
            
            return caractercambiado;
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        area1 = new javax.swing.JTextField();
        area2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        areaorienta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        areacaracter = new javax.swing.JTextField();
        rotar = new javax.swing.JButton();
        encriptar = new javax.swing.JButton();
        desencriptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(area1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, -1));

        area2.setEditable(false);
        getContentPane().add(area2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 110, -1));

        jLabel1.setText("Orientacion(1/2)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));
        getContentPane().add(areaorienta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 70, -1));

        jLabel2.setText("nº caracteres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));
        getContentPane().add(areacaracter, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 50, -1));

        rotar.setText("Rotar");
        rotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotarActionPerformed(evt);
            }
        });
        getContentPane().add(rotar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        encriptar.setText("Encriptar");
        encriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encriptarActionPerformed(evt);
            }
        });
        getContentPane().add(encriptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        desencriptar.setText("Desencriptar");
        desencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desencriptarActionPerformed(evt);
            }
        });
        getContentPane().add(desencriptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotarActionPerformed
        
       
    }//GEN-LAST:event_rotarActionPerformed

    private void encriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encriptarActionPerformed
        // TODO add your handling code here:
        int rotacion=Integer.parseInt(areaorienta.getText());
         int caracteres=Integer.parseInt(areacaracter.getText());
         encriptaCadena(rotacion,caracteres);
    }//GEN-LAST:event_encriptarActionPerformed

    private void desencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desencriptarActionPerformed
        // TODO add your handling code here:
        int rotacion=Integer.parseInt(areaorienta.getText());
         int caracteres=Integer.parseInt(areacaracter.getText());
         desencriptaCadena(rotacion,caracteres);
    }//GEN-LAST:event_desencriptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadenas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area1;
    private javax.swing.JTextField area2;
    private javax.swing.JTextField areacaracter;
    private javax.swing.JTextField areaorienta;
    private javax.swing.JButton desencriptar;
    private javax.swing.JButton encriptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton rotar;
    // End of variables declaration//GEN-END:variables
}
