
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alvaro
 */
public class EventosVentana extends javax.swing.JFrame {
int rojo,verde,azul;
    /**
     * Creates new form EventosVentana
     */
    public EventosVentana() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tverde = new javax.swing.JLabel();
        barrarojo = new javax.swing.JScrollBar();
        jLabel2 = new javax.swing.JLabel();
        trojo = new javax.swing.JLabel();
        barraverde = new javax.swing.JScrollBar();
        jLabel3 = new javax.swing.JLabel();
        tazul = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        barraazul = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Verde:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        tverde.setText("0");
        getContentPane().add(tverde, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 40, -1));

        barrarojo.setMaximum(265);
        barrarojo.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        barrarojo.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                barrarojoAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(barrarojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 360, 30));

        jLabel2.setText("Rojo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        trojo.setText("0");
        getContentPane().add(trojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 30, -1));

        barraverde.setMaximum(265);
        barraverde.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        barraverde.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                barraverdeAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(barraverde, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 360, 30));

        jLabel3.setText("Azul:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        tazul.setText("0");
        getContentPane().add(tazul, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 40, -1));

        panel.setBackground(new java.awt.Color(0, 0, 0));
        panel.setForeground(new java.awt.Color(0, 0, 0));
        panel.setToolTipText("");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 620, 160));

        barraazul.setMaximum(265);
        barraazul.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        barraazul.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                barraazulAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(barraazul, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 313, 360, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barrarojoAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_barrarojoAdjustmentValueChanged
        // TODO add your handling code here:
        rojo=barrarojo.getValue();
        trojo.setText(rojo+"");
        panel.setBackground(new Color(rojo,verde,azul));
    }//GEN-LAST:event_barrarojoAdjustmentValueChanged

    private void barraverdeAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_barraverdeAdjustmentValueChanged
        // TODO add your handling code here:
        verde=barraverde.getValue();
        tverde.setText(verde+"");
        panel.setBackground(new Color(rojo,verde,azul));
    }//GEN-LAST:event_barraverdeAdjustmentValueChanged

    private void barraazulAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_barraazulAdjustmentValueChanged
        // TODO add your handling code here:
        azul=barraazul.getValue();
        tazul.setText(azul+"");
        panel.setBackground(new Color(rojo,verde,azul));
    }//GEN-LAST:event_barraazulAdjustmentValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventosVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventosVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventosVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventosVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventosVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar barraazul;
    private javax.swing.JScrollBar barrarojo;
    private javax.swing.JScrollBar barraverde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel tazul;
    private javax.swing.JLabel trojo;
    private javax.swing.JLabel tverde;
    // End of variables declaration//GEN-END:variables
}
