/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alvaro
 */
public class FuncionesMatematicas extends javax.swing.JFrame {

    /**
     * Creates new form FuncionesMatematicas
     */
    public FuncionesMatematicas() {
        initComponents();
        framefactorial.pack();
        frameeuler.pack();
        frameprimos.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framefactorial = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numerofactorial = new javax.swing.JTextField();
        factorial = new javax.swing.JTextField();
        calcularfactorial = new javax.swing.JButton();
        limpiarfactorial = new javax.swing.JButton();
        frameprimos = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaprimos = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        calcularprimos = new javax.swing.JButton();
        limpiarprimos = new javax.swing.JButton();
        desde = new javax.swing.JTextField();
        hasta = new javax.swing.JTextField();
        frameeuler = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numeroeuler = new javax.swing.JTextField();
        euler = new javax.swing.JTextField();
        calculareuler = new javax.swing.JButton();
        limpiareuler = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        framefactorial.setTitle("Calculo de factorial");
        framefactorial.setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setText("Numero");

        jLabel2.setText("Factorial");

        factorial.setEditable(false);

        calcularfactorial.setText("Calcular");
        calcularfactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularfactorialActionPerformed(evt);
            }
        });

        limpiarfactorial.setText("Limpiar");
        limpiarfactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarfactorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout framefactorialLayout = new javax.swing.GroupLayout(framefactorial.getContentPane());
        framefactorial.getContentPane().setLayout(framefactorialLayout);
        framefactorialLayout.setHorizontalGroup(
            framefactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framefactorialLayout.createSequentialGroup()
                .addGroup(framefactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framefactorialLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(framefactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(framefactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numerofactorial)
                            .addComponent(factorial, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                    .addGroup(framefactorialLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(calcularfactorial)
                        .addGap(51, 51, 51)
                        .addComponent(limpiarfactorial)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        framefactorialLayout.setVerticalGroup(
            framefactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framefactorialLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(framefactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numerofactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(framefactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(factorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(framefactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularfactorial)
                    .addComponent(limpiarfactorial))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        frameprimos.setTitle("Calculo de primos");
        frameprimos.setBackground(new java.awt.Color(0, 255, 0));

        jLabel3.setText("Desde:");

        jLabel4.setText("Hasta:");

        areaprimos.setEditable(false);
        areaprimos.setColumns(20);
        areaprimos.setRows(5);
        jScrollPane1.setViewportView(areaprimos);

        jLabel5.setText("Nº primos:");

        calcularprimos.setText("Calcular");
        calcularprimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularprimosActionPerformed(evt);
            }
        });

        limpiarprimos.setText("Limpiar");
        limpiarprimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarprimosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameprimosLayout = new javax.swing.GroupLayout(frameprimos.getContentPane());
        frameprimos.getContentPane().setLayout(frameprimosLayout);
        frameprimosLayout.setHorizontalGroup(
            frameprimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameprimosLayout.createSequentialGroup()
                .addGroup(frameprimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frameprimosLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(frameprimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(frameprimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desde)
                            .addComponent(hasta))
                        .addGap(15, 15, 15))
                    .addGroup(frameprimosLayout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addGroup(frameprimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameprimosLayout.createSequentialGroup()
                                .addComponent(calcularprimos)
                                .addGap(31, 31, 31)
                                .addComponent(limpiarprimos))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74))
        );
        frameprimosLayout.setVerticalGroup(
            frameprimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameprimosLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(frameprimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(frameprimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(frameprimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameprimosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(frameprimosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calcularprimos)
                            .addComponent(limpiarprimos))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameprimosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(157, 157, 157))))
        );

        frameeuler.setTitle("Calculo de Euler");
        frameeuler.setBackground(new java.awt.Color(0, 255, 0));

        jLabel6.setText("Numero:");

        jLabel7.setText("Euler:");

        euler.setEditable(false);

        calculareuler.setText("Calcular");
        calculareuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculareulerActionPerformed(evt);
            }
        });

        limpiareuler.setText("Limpiar");
        limpiareuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiareulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameeulerLayout = new javax.swing.GroupLayout(frameeuler.getContentPane());
        frameeuler.getContentPane().setLayout(frameeulerLayout);
        frameeulerLayout.setHorizontalGroup(
            frameeulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameeulerLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(frameeulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameeulerLayout.createSequentialGroup()
                        .addComponent(calculareuler)
                        .addGap(29, 29, 29)
                        .addComponent(limpiareuler))
                    .addGroup(frameeulerLayout.createSequentialGroup()
                        .addGroup(frameeulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(36, 36, 36)
                        .addGroup(frameeulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numeroeuler)
                            .addComponent(euler, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        frameeulerLayout.setVerticalGroup(
            frameeulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameeulerLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(frameeulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numeroeuler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(frameeulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(euler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(frameeulerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculareuler)
                    .addComponent(limpiareuler))
                .addGap(37, 37, 37))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funciones matematicas");

        jMenu1.setText("Opciones");

        jMenuItem1.setText("Factorial de un numero");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Numeros primos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Funcion de euler");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        framefactorial.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        frameprimos.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        frameeuler.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void calcularfactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularfactorialActionPerformed
        // TODO add your handling code here:
        factorial.setText(Mate.factorial(Integer.parseInt(numerofactorial.getText()))+"");
    }//GEN-LAST:event_calcularfactorialActionPerformed

    private void limpiarfactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarfactorialActionPerformed
        // TODO add your handling code here:
        factorial.setText(null);
        numerofactorial.setText(null);
    }//GEN-LAST:event_limpiarfactorialActionPerformed

    private void calcularprimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularprimosActionPerformed
        // TODO add your handling code here:
        int numdesde=Integer.parseInt(desde.getText());
        int numhasta=Integer.parseInt(hasta.getText());
        
        for(int i=numdesde;i<=numhasta;i++){
            if(Mate.primo(i)){
                areaprimos.append(i+"\n");
            }
        }
        
    }//GEN-LAST:event_calcularprimosActionPerformed

    private void limpiarprimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarprimosActionPerformed
        // TODO add your handling code here:
        desde.setText(null);
        hasta.setText(null);
        areaprimos.setText(null);
    }//GEN-LAST:event_limpiarprimosActionPerformed

    private void calculareulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculareulerActionPerformed
        // TODO add your handling code here:
        euler.setText(Mate.euler(Integer.parseInt(numeroeuler.getText()))+"");
    }//GEN-LAST:event_calculareulerActionPerformed

    private void limpiareulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiareulerActionPerformed
        // TODO add your handling code here:
        numeroeuler.setText(null);
        euler.setText(null);
    }//GEN-LAST:event_limpiareulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionesMatematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionesMatematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionesMatematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionesMatematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionesMatematicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaprimos;
    private javax.swing.JButton calculareuler;
    private javax.swing.JButton calcularfactorial;
    private javax.swing.JButton calcularprimos;
    private javax.swing.JTextField desde;
    private javax.swing.JTextField euler;
    private javax.swing.JTextField factorial;
    private javax.swing.JFrame frameeuler;
    private javax.swing.JFrame framefactorial;
    private javax.swing.JFrame frameprimos;
    private javax.swing.JTextField hasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiareuler;
    private javax.swing.JButton limpiarfactorial;
    private javax.swing.JButton limpiarprimos;
    private javax.swing.JTextField numeroeuler;
    private javax.swing.JTextField numerofactorial;
    // End of variables declaration//GEN-END:variables
}
