
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alvar
 */
public class PracticaConsumo extends javax.swing.JFrame {
    DefaultTableModel modelo;
    AgendaBD agenda;
    
    /**
     * Creates new form PracticaConsumo
     */
    public PracticaConsumo() {
        initComponents();
        agenda = new AgendaBD();
        rellenarListaDesplegable();
        generarTabla();
    }

     public void generarTabla(){
        modelo=new DefaultTableModel();
        modelo.addColumn("Articulo");
         modelo.addColumn("Unidades");
          modelo.addColumn("PVP");
          modelo.addColumn("Importe");
               tabla.setModel(modelo);
    }
    public void agregarFila(){
        modelo.addRow(new Object[tabla.getColumnCount()]);
    }
    public void visualizarConsumos(){
        String fecha=areafecha.getText();
       String barra=(String) combo.getSelectedItem();
    ResultSet res= agenda.obtenerConsumos(barra,fecha);
    ResultSet res2= agenda.obtenerImportes(barra, fecha);
    int fila=0;
       if(res!=null){
           try{
               while(res.next()){
                   agregarFila();
                   System.out.println(res.getString("Articulo"));
                   System.out.println(res.getString("Unidades"));
                   System.out.println(res.getString("PVP"));
                  modelo.setValueAt(res.getString("Articulo"),fila ,0);
                  modelo.setValueAt(res.getString("Unidades"),fila ,1);
                  modelo.setValueAt(res.getString("PVP"),fila ,2);             
                   fila++;
               }
           }catch(SQLException e){}
       }
       fila=0;
       if(res2!=null){
           try{
               while(res2.next()){
                   System.out.println(res2.getString("Importe"));
                   modelo.setValueAt(res2.getString("Importe"), fila, 3);
                   fila++;
               }
           }catch(SQLException e){}
       }
       Double suma=0.0;
       
       for (int i=0;i<modelo.getRowCount();i++){
           
           String penalizaciones=(String)(modelo.getValueAt(i, 3));
           suma=suma+(Double.parseDouble(penalizaciones));
           importes.setText(suma+"");
       }
    }
     public void rellenarListaDesplegable(){
        ResultSet res=agenda.obtenerRegistros("Barras");
        if(res!=null){
            try{
                combo.removeAllItems();
                while(res.next()){
                    combo.addItem(res.getString("barra"));
                }
            }catch(SQLException e){
                System.out.println("Error");
            }
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        areafecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        importes = new javax.swing.JLabel();
        consultar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 200, -1));

        jLabel1.setText("Barra");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel2.setText("Fecha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        areafecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        areafecha.setText("YYY/MM/DD");
        areafecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areafechaActionPerformed(evt);
            }
        });
        getContentPane().add(areafecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 100, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Unidades", "PVP", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 650, 140));

        jLabel3.setText("Total importe ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        importes.setForeground(new java.awt.Color(255, 0, 0));
        importes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importes.setText("0");
        getContentPane().add(importes, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 30, 20));

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        // TODO add your handling code here:
        if(tabla.getRowCount()!=0)
        {
            modelo.setRowCount(0);
        }    
        
    }//GEN-LAST:event_comboItemStateChanged

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        visualizarConsumos();
    }//GEN-LAST:event_consultarActionPerformed

    private void areafechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areafechaActionPerformed
        // TODO add your handling code here:
        visualizarConsumos();
    }//GEN-LAST:event_areafechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticaConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticaConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticaConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticaConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticaConsumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areafecha;
    private javax.swing.JComboBox combo;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel importes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
