/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica10;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author alvar
 */
public class TablaDinamica extends javax.swing.JFrame {

 
   DefaultTableModel modelo,modelo2;
    
    public TablaDinamica() {
        initComponents();
        modelo=new DefaultTableModel();
        modelo= (DefaultTableModel) tabla1.getModel();
    
        
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        Siguiente = new javax.swing.JButton();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        añadirfila = new javax.swing.JButton();
        eliminarfila = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        nuevacolumna = new javax.swing.JButton();
        cambiarnombres = new javax.swing.JButton();
        eliminarcloumna = new javax.swing.JButton();
        area = new javax.swing.JTextField();

        dialogo.setMinimumSize(new java.awt.Dimension(500, 500));
        dialogo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label1.setText("Cambia el nombre de las columna y y pulsa siguiente");
        dialogo.getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla2);

        dialogo.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 80));

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        dialogo.getContentPane().add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        label2.setText("Pulsar \"Enter\" para realizar los cambios");
        dialogo.getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Columna 1", "Columna 2", "Columna 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla1.setRowHeight(25);
        jScrollPane1.setViewportView(tabla1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 120));

        añadirfila.setText("Añadir Fila");
        añadirfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirfilaActionPerformed(evt);
            }
        });
        getContentPane().add(añadirfila, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        eliminarfila.setText("Eliminar Fila");
        eliminarfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarfilaActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarfila, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        nuevacolumna.setText("Nueva Columna");
        nuevacolumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevacolumnaActionPerformed(evt);
            }
        });
        getContentPane().add(nuevacolumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        cambiarnombres.setText("Cambiar Nombres de Columnas");
        cambiarnombres.setToolTipText("");
        cambiarnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarnombresActionPerformed(evt);
            }
        });
        getContentPane().add(cambiarnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        eliminarcloumna.setText("Borrar Columna");
        eliminarcloumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcloumnaActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarcloumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));
        getContentPane().add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents



   
      public void cambiarColumnas(){
        modelo2 = new DefaultTableModel();
        int nCol=modelo.getColumnCount();
        for(int i=1; i<= nCol; i++){
            modelo2.addColumn("Columna -" + i);
            Object[] fila = new Object[nCol];
            modelo2.addRow(fila);
        }
        for(int i=0; i<nCol; i++){
            modelo2.setValueAt(modelo.getColumnName(i),0,i);
            tabla2.setModel(modelo2);
            
                
        }
        dialogo.pack();
        dialogo.setVisible(true);
    }
       public void cambiarIdentificadores(){
        Vector identif = new Vector();
        for(int i=0 ; i<modelo2.getColumnCount();i++){
            identif.add(tabla2.getValueAt(0, i));
        }
        modelo.setColumnIdentifiers(identif);
    }
    private void añadirfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirfilaActionPerformed
        // TODO add your handling code here:
               
               modelo.addRow(new Object[tabla1.getColumnCount()]);
    }//GEN-LAST:event_añadirfilaActionPerformed

    private void eliminarfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarfilaActionPerformed
        // TODO add your handling code here:
        try{
        modelo.removeRow(tabla1.getSelectedRow());}
        catch(ArrayIndexOutOfBoundsException e){
            System.out.println("Error, no se ha selecionado nada");
        }
        
    }//GEN-LAST:event_eliminarfilaActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
       try{ 
           do{
            modelo.removeRow(0);
            }while(modelo.getRowCount()!=0);
       }
       catch(ArrayIndexOutOfBoundsException e){
           System.out.println("Error, no hay nada para limpiar");
       }
        
        
    }//GEN-LAST:event_limpiarActionPerformed

    private void nuevacolumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevacolumnaActionPerformed
        // TODO add your handling code here:
        if ("".equals(area.getText())){
            System.out.println("Error, no se ha introducido nombre");
        }else{
        modelo.addColumn(area.getText());        
        }
    }//GEN-LAST:event_nuevacolumnaActionPerformed

    private void eliminarcloumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcloumnaActionPerformed
        // TODO add your handling code here:     
       if(modelo.getColumnCount()>0)
       {
           modelo.setColumnCount(modelo.getColumnCount()-1);
       }else{System.out.println("Error, no queda ninguna columna");}
    }//GEN-LAST:event_eliminarcloumnaActionPerformed

    private void cambiarnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarnombresActionPerformed
        // TODO add your handling code here:
        
        cambiarColumnas();
        
    }//GEN-LAST:event_cambiarnombresActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
        cambiarIdentificadores();
        dialogo.dispose();
        
    }//GEN-LAST:event_SiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaDinamica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaDinamica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaDinamica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaDinamica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaDinamica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton Siguiente;
    protected javax.swing.JTextField area;
    protected javax.swing.JButton añadirfila;
    protected javax.swing.JButton cambiarnombres;
    protected javax.swing.JDialog dialogo;
    protected javax.swing.JButton eliminarcloumna;
    protected javax.swing.JButton eliminarfila;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JScrollPane jScrollPane2;
    protected java.awt.Label label1;
    protected java.awt.Label label2;
    protected javax.swing.JButton limpiar;
    protected javax.swing.JButton nuevacolumna;
    protected javax.swing.JTable tabla1;
    protected javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
