/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor;

/**
 *
 * @author alvar
 */
public class Conversor extends java.awt.Frame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        euro = new java.awt.TextField();
        label2 = new java.awt.Label();
        dollar = new java.awt.TextField();
        label3 = new java.awt.Label();
        libra = new java.awt.TextField();
        limpiar = new java.awt.Button();
        salir = new java.awt.Button();

        setMinimumSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setText("€");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 30, 40));

        euro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        euro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                euroKeyReleased(evt);
            }
        });
        add(euro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 60, 30));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label2.setText("£");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 30, 40));

        dollar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dollarKeyReleased(evt);
            }
        });
        add(dollar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 60, 30));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label3.setText("$");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        libra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                libraKeyReleased(evt);
            }
        });
        add(libra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 60, 30));

        limpiar.setLabel("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        salir.setLabel("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        euro.setText("");
        dollar.setText("");
        libra.setText("");
        euro.requestFocus();
    }//GEN-LAST:event_limpiarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void euroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_euroKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            System.exit(0);
        }
        try{
            euro();
        }catch(NumberFormatException e)
        {
            dollar.setText("");
            libra.setText("");
        }
        
            
    }//GEN-LAST:event_euroKeyReleased

    private void libraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_libraKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            System.exit(0);
        }
        try{
            libra();
        }catch(NumberFormatException e)
        {
            dollar.setText("");
            euro.setText("");
        }
    }//GEN-LAST:event_libraKeyReleased

    private void dollarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dollarKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            System.exit(0);
        }
        try{
            dollar();
        }catch(NumberFormatException e)
        {
           libra.setText("");
            euro.setText("");
        }
    }//GEN-LAST:event_dollarKeyReleased

    private void euro(){
        
        dollar.setText("");
        libra.setText("");
        double euro_conv=Double.parseDouble(euro.getText());
        dollar.setText((euro_conv*1.23)+"");
        libra.setText((euro_conv*0.88)+"");
    }
    private void dollar(){
        
        euro.setText("");
        libra.setText("");
        double dollar_conv=Double.parseDouble(dollar.getText());
        euro.setText((dollar_conv*0.81)+"");
        libra.setText((dollar_conv*0.72)+"");
    }
    private void libra(){
        
        euro.setText("");
        dollar.setText("");
        double libra_conv=Double.parseDouble(libra.getText());
        euro.setText((libra_conv*1.13)+"");
        dollar.setText((libra_conv*1.39)+"");
    }

//euro a dollar *1.23   a libra *0.88
//dolar a euro *0.81 a libra *0.72
// libra a euro 1.13 A dolar *1.39
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected java.awt.TextField dollar;
    protected java.awt.TextField euro;
    protected java.awt.Label label1;
    protected java.awt.Label label2;
    protected java.awt.Label label3;
    protected java.awt.TextField libra;
    protected java.awt.Button limpiar;
    protected java.awt.Button salir;
    // End of variables declaration//GEN-END:variables
}
