/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import java.util.ArrayList;

/**
 *
 * @author alvar
 */
public class EjVoluntario extends java.awt.Frame {

    ArrayList<Voluntario> notas= new ArrayList<Voluntario>();
    /**
     * Creates new form EjVoluntario
     */
    public EjVoluntario() {
        initComponents();
    }

    
    
    public void nuevaNota()
    {
        
        Voluntario nota=new Voluntario();
         nota.setNota(Double.parseDouble(tnota.getText()));
         notas.add(nota);
         cont++;
         contador.setText(cont+"");
         tnota.setText(null);
         tnota.requestFocus();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoe = new javax.swing.JDialog();
        label4 = new java.awt.Label();
        aceptar = new java.awt.Button();
        label1 = new java.awt.Label();
        tnota = new java.awt.TextField();
        label2 = new java.awt.Label();
        contador = new java.awt.TextField();
        label3 = new java.awt.Label();
        notamedia = new java.awt.TextField();
        añadir = new java.awt.Button();
        calcular = new java.awt.Button();
        nueva = new java.awt.Button();

        dialogoe.setMinimumSize(new java.awt.Dimension(500, 500));
        dialogoe.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label4.setText("Error en la introduccion de la nota");
        dialogoe.getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        aceptar.setLabel("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        dialogoe.getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        setMinimumSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("Nota");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        tnota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnotaActionPerformed(evt);
            }
        });
        add(tnota, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 50, -1));

        label2.setText("Contador");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        contador.setEditable(false);
        add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 70, -1));

        label3.setText("Notamedia");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        notamedia.setEditable(false);
        add(notamedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 50, 20));

        añadir.setLabel("Añadir");
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });
        add(añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        calcular.setLabel("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        nueva.setLabel("Nuevo");
        nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaActionPerformed(evt);
            }
        });
        add(nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:

        Voluntario nota2 = new Voluntario();
       for(int i=0;i<=cont-1;i++){
           nota2 = notas.get(i);
           sum=sum+nota2.getNota();
       }
       notamedia.setText((sum/cont)+"");
    }//GEN-LAST:event_calcularActionPerformed

    private void nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaActionPerformed
        // TODO add your handling code here:
        
        notas.clear();    
        tnota.setText(null);
        contador.setText(null);
        notamedia.setText(null);
        cont=0;
        sum=0;
        tnota.requestFocus();
        
    }//GEN-LAST:event_nuevaActionPerformed

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
        // TODO add your handling code here:
        try{
            if (Double.parseDouble(tnota.getText())>=0 && Double.parseDouble(tnota.getText())<=10){
            nuevaNota();}
            else
                dialogoe.show();
                
        }catch (IllegalArgumentException u)
        {
            
            dialogoe.show();
            
            
        }
    }//GEN-LAST:event_añadirActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        tnota.setText(null);
        tnota.requestFocus();
        dialogoe.dispose();
    }//GEN-LAST:event_aceptarActionPerformed

    private void tnotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnotaActionPerformed
        // TODO add your handling code here:
        try{
            nuevaNota();
        }catch (IllegalArgumentException u)
        {
            dialogoe.show();
            
        }
    }//GEN-LAST:event_tnotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjVoluntario().setVisible(true);
            }
        });
    }
    protected double sum;
    protected int cont;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected java.awt.Button aceptar;
    protected java.awt.Button añadir;
    protected java.awt.Button calcular;
    protected java.awt.TextField contador;
    protected javax.swing.JDialog dialogoe;
    protected java.awt.Label label1;
    protected java.awt.Label label2;
    protected java.awt.Label label3;
    protected java.awt.Label label4;
    protected java.awt.TextField notamedia;
    protected java.awt.Button nueva;
    protected java.awt.TextField tnota;
    // End of variables declaration//GEN-END:variables
}
