/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author alvar
 */
public class Practica7 extends java.awt.Frame {
    ArrayList<TPersona> persona1= new ArrayList<TPersona>();
    /**
     * Creates new form Practica7
     */
    public Practica7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoe2 = new javax.swing.JDialog();
        label8 = new java.awt.Label();
        aceptar2 = new java.awt.Button();
        dialogo3 = new javax.swing.JDialog();
        label9 = new java.awt.Label();
        aceptar3 = new java.awt.Button();
        dialogoerrorborrar = new javax.swing.JDialog();
        label10 = new java.awt.Label();
        aceptar4 = new java.awt.Button();
        dialogoseguridad = new javax.swing.JDialog();
        label11 = new java.awt.Label();
        si = new java.awt.Button();
        no = new java.awt.Button();
        label1 = new java.awt.Label();
        choice = new java.awt.Choice();
        borrar = new java.awt.Button();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        nuevo = new java.awt.Button();
        nombre = new java.awt.TextField();
        direccion = new java.awt.TextField();
        edad = new java.awt.TextField();
        telefono = new java.awt.TextField();

        dialogoe2.setMinimumSize(new java.awt.Dimension(500, 500));
        dialogoe2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label8.setText("Debe rellenar todos los campos");
        dialogoe2.getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, -1));

        aceptar2.setLabel("Aceptar");
        aceptar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar2ActionPerformed(evt);
            }
        });
        dialogoe2.getContentPane().add(aceptar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        dialogo3.setMinimumSize(new java.awt.Dimension(500, 500));
        dialogo3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label9.setText("Introduccion de los valores incorrecta");
        dialogo3.getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        aceptar3.setLabel("Aceptar");
        aceptar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar3ActionPerformed(evt);
            }
        });
        dialogo3.getContentPane().add(aceptar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        dialogoerrorborrar.setMinimumSize(new java.awt.Dimension(500, 500));
        dialogoerrorborrar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label10.setText("No hay ningun item en la lista");
        dialogoerrorborrar.getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 350, -1));

        aceptar4.setLabel("Aceptar");
        aceptar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar4ActionPerformed(evt);
            }
        });
        dialogoerrorborrar.getContentPane().add(aceptar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        dialogoseguridad.setMinimumSize(new java.awt.Dimension(500, 500));
        dialogoseguridad.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label11.setAlignment(java.awt.Label.CENTER);
        label11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label11.setText("Esta seguro de que desea eliminar el contacto");
        dialogoseguridad.getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        si.setLabel("Si");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });
        dialogoseguridad.getContentPane().add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 184, 50, 40));

        no.setLabel("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        dialogoseguridad.getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 184, 50, 40));

        setMinimumSize(new java.awt.Dimension(500, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("Seleccionar");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        choice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choiceItemStateChanged(evt);
            }
        });
        add(choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 180, -1));

        borrar.setLabel("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        label2.setText("Datos de contacto");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        label3.setText("Nombre");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        label4.setText("Direccion");
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        label5.setText("Edad");
        add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        label6.setText("Telefono");
        add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        nuevo.setLabel("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreKeyReleased(evt);
            }
        });
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, -1));

        direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                direccionKeyReleased(evt);
            }
        });
        add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 170, -1));

        edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edadKeyReleased(evt);
            }
        });
        add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 70, -1));

        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefonoKeyReleased(evt);
            }
        });
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    public void nuevoContacto()
    {
        TPersona persona =new TPersona();
        persona.setNombre(nombre.getText());
        persona.setDireccion(direccion.getText());
        persona.setEdad(Integer.parseInt(edad.getText()));
        persona.setTelefono(Integer.parseInt(telefono.getText()));
        persona1.add(persona);
        choice.addItem(persona.getNombre());
        nombre.setText(null);
        direccion.setText(null);
        edad.setText(null);
        telefono.setText(null);
        System.out.println(persona1.size());
        
        
    }
    
    public void borrarContacto() {                                
        
        if (choice.getItemCount() > 0) {
            dialogoseguridad.show();
        }else{
            dialogoerrorborrar.show();
        }
    }
        
    
    
    
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        //choice.remove(choice.getSelectedItem());
       borrarContacto();
    }//GEN-LAST:event_borrarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        try{
            nuevoContacto();
        }catch (IllegalArgumentException u)
        {
            dialogoe2.show();
        }
        /*catch (NumberFormatException e)
        {
            dialogo3.show();
        }
        finally {}*/
        
        
    }//GEN-LAST:event_nuevoActionPerformed

    private void choiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choiceItemStateChanged
        // TODO add your handling code here:
        TPersona persona2 = new TPersona();
        persona2 = persona1.get(choice.getSelectedIndex());
        nombre.setText(persona2.getNombre());
        direccion.setText(persona2.getDireccion());
        telefono.setText(Integer.toString(persona2.getTelefono()));
        edad.setText(Integer.toString(persona2.getEdad()));
        nombre.requestFocus();
    }//GEN-LAST:event_choiceItemStateChanged

    private void aceptar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar2ActionPerformed
        // TODO add your handling code here:
        dialogoe2.dispose();
            if("".equals(nombre.getText())){
                 nombre.requestFocus();
             }
            if("".equals(direccion.getText())){
                 direccion.requestFocus();
             }
            if("".equals(edad.getText())){
                 edad.requestFocus();
             }
            if("".equals(telefono.getText())){
                 telefono.requestFocus();
             }
    }//GEN-LAST:event_aceptar2ActionPerformed

    private void aceptar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar3ActionPerformed
        // TODO add your handling code here:
        dialogo3.dispose();
    }//GEN-LAST:event_aceptar3ActionPerformed

    private void aceptar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar4ActionPerformed
        // TODO add your handling code here:
        dialogoerrorborrar.dispose();
    }//GEN-LAST:event_aceptar4ActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
        dialogoseguridad.dispose();
    }//GEN-LAST:event_noActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        // TODO add your handling code here:
        
        persona1.remove( choice.getSelectedIndex() );
       choice.remove( choice.getSelectedIndex() );        

        nombre.setText(null);
        direccion.setText(null);
        edad.setText(null);
        telefono.setText(null);
        nombre.requestFocus();
        dialogoseguridad.dispose();
    }//GEN-LAST:event_siActionPerformed

    private void nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            direccion.requestFocus();
        }
    }//GEN-LAST:event_nombreKeyReleased

    private void direccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            edad.requestFocus();
        }
    }//GEN-LAST:event_direccionKeyReleased

    private void edadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edadKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            telefono.requestFocus();
        }
    }//GEN-LAST:event_edadKeyReleased

    private void telefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            nombre.requestFocus();
        }
    }//GEN-LAST:event_telefonoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica7().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected java.awt.Button aceptar2;
    protected java.awt.Button aceptar3;
    protected java.awt.Button aceptar4;
    protected java.awt.Button borrar;
    protected java.awt.Choice choice;
    protected javax.swing.JDialog dialogo3;
    protected javax.swing.JDialog dialogoe2;
    protected javax.swing.JDialog dialogoerrorborrar;
    protected javax.swing.JDialog dialogoseguridad;
    protected java.awt.TextField direccion;
    protected java.awt.TextField edad;
    protected java.awt.Label label1;
    protected java.awt.Label label10;
    protected java.awt.Label label11;
    protected java.awt.Label label2;
    protected java.awt.Label label3;
    protected java.awt.Label label4;
    protected java.awt.Label label5;
    protected java.awt.Label label6;
    protected java.awt.Label label8;
    protected java.awt.Label label9;
    protected java.awt.Button no;
    protected java.awt.TextField nombre;
    protected java.awt.Button nuevo;
    protected java.awt.Button si;
    protected java.awt.TextField telefono;
    // End of variables declaration//GEN-END:variables
}
