/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alvar
 */
public class Ejercicio2 extends java.awt.Frame {

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
        for (int i=1;i<=31;i++)
            choice1.addItem(i+"");
        for (int i=1;i<=12;i++){
            switch (i){
            case 1:  choice2.addItem("Enero");
                     break;
            case 2:  choice2.addItem("Febrero");
                     break;
            case 3:  choice2.addItem("Marzo");
                     break;
            case 4:  choice2.addItem("Abril");
                     break;
            case 5:  choice2.addItem("Mayo");
                     break;
            case 6:  choice2.addItem("Junio");
                     break;
            case 7:  choice2.addItem("Julio");
                     break;
            case 8:  choice2.addItem("Agosto");
                     break;
            case 9:  choice2.addItem("Septiembre");
                     break;
            case 10: choice2.addItem("Octubre");
                     break;
            case 11: choice2.addItem("Noviembre");
                     break;
            case 12: choice2.addItem("Diciembre");
                     break;
            }
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        choice2 = new java.awt.Choice();
        scrollbar1 = new java.awt.Scrollbar();
        button1 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Dia");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel2.setText("Mes");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));
        add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 60, 40));
        add(choice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 130, 40));

        scrollbar1.setMaximum(365);
        scrollbar1.setOrientation(java.awt.Scrollbar.HORIZONTAL);
        scrollbar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrollbar1AdjustmentValueChanged(evt);
            }
        });
        add(scrollbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 126, 190, 50));

        button1.setLabel("Resetear");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void scrollbar1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrollbar1AdjustmentValueChanged
        // TODO add your handling code here:
          
                 if (scrollbar1.getValue()<=30)
                 {
                     choice1.select(scrollbar1.getValue());
                     choice2.select(0);
                 }else
                     if(scrollbar1.getValue()<=58)
                     {
                        choice1.select(scrollbar1.getValue()-31);
                        choice2.select(1);
                     }else
                        if(scrollbar1.getValue()<=89)
                        {
                            choice1.select(scrollbar1.getValue()-59);
                            choice2.select(2);
                        }else
                            if(scrollbar1.getValue()<=120)
                            {
                                choice1.select(scrollbar1.getValue()-90);
                                choice2.select(3);
                            }else
                                if(scrollbar1.getValue()<=151)
                                {
                                    choice1.select(scrollbar1.getValue()-121);
                                    choice2.select(5);
                                }else
                                    if(scrollbar1.getValue()<=181)
                                    {   
                                        choice1.select(scrollbar1.getValue()-152);
                                        choice2.select(6);
                                    }else
                                        if(scrollbar1.getValue()<=212)
                                        {   
                                            choice1.select(scrollbar1.getValue()-182);
                                            choice2.select(7);
                                        }else
                                            if(scrollbar1.getValue()<=243)
                                            {   
                                                choice1.select(scrollbar1.getValue()-213);
                                                choice2.select(8);
                                            }else
                                                if(scrollbar1.getValue()<=273)
                                                {   
                                                    choice1.select(scrollbar1.getValue()-244);
                                                    choice2.select(9);
                                                }else
                                                    if(scrollbar1.getValue()<=304)
                                                    {   
                                                     choice1.select(scrollbar1.getValue()-274);
                                                     choice2.select(10);
                                                    }else
                                                        if(scrollbar1.getValue()<=334)
                                                        {   
                                                            choice1.select(scrollbar1.getValue()-305);
                                                            choice2.select(11);
                                                        }
                                                           
          
                        
        
    }//GEN-LAST:event_scrollbar1AdjustmentValueChanged

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
         
           
       choice1.select(0);
       choice2.select(0);
       scrollbar1.setValue(0);
        
                    
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }
private int valor;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Scrollbar scrollbar1;
    // End of variables declaration//GEN-END:variables
}
