
import java.sql.*;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alvar
 */
public class Camiones2 extends javax.swing.JFrame {
CamionesBD camiones;
DefaultTableModel modelo;
    /**
     * Creates new form Camiones2
     */
    public Camiones2() {
        initComponents();
        camiones=new CamionesBD();
        modelo=new DefaultTableModel();
        rellenarListaConductores();       
        generarTabla();
    }

    
    
    public void rellenarListaConductores(){
        comboconductor.removeAllItems();
        ResultSet resultado = camiones.obtenerTabla("conductores","nombre");
        if(resultado!=null){
        try{
            while(resultado.next()){
                comboconductor.addItem(resultado.getString("nombre"));
            }
        }catch(SQLException e){}
        comboconductor.setSelectedIndex(0);
        }
        
    }
    public void establecerDatos(){
        areanif.setText("");
        areadireccion.setText("");
        String nombre=(String)comboconductor.getSelectedItem();
        ResultSet resultado = camiones.establecerDatosConductor(nombre);
        if(resultado!=null){
        try{
            while(resultado.next()){
                areanif.setText(resultado.getString("nif"));
                areadireccion.setText(resultado.getString("direccion"));
            }
        }catch(SQLException e){}
        
        }
    }
    
    public void generarTabla(){
        modelo.addColumn("Matricula");
         modelo.addColumn("Marca");
          modelo.addColumn("Modelo");
          modelo.addColumn("Kilometros");
          modelo.addColumn("Fecha");
               tabla.setModel(modelo);
    }
    public void agregarFila(){
        modelo.addRow(new Object[tabla.getColumnCount()]);
    }
    
     public void obtenerResultados(){
        String nombre=(String)comboconductor.getSelectedItem();
        String fecha1=areafecha1.getText();
        String fecha2=areafecha2.getText();
        ResultSet res=camiones.establecerDatosTabla2(nombre, fecha1, fecha2);
        int fila=0;
        if(res!=null){
            try{
                while(res.next()){
                    agregarFila();
                    modelo.setValueAt(res.getString("matricula"), fila, 0);
                    modelo.setValueAt(res.getString("marca"), fila, 1);
                    modelo.setValueAt(res.getString("modelo"), fila, 2);
                    modelo.setValueAt(res.getString("km"), fila, 3);
                    modelo.setValueAt(res.getString("fecha"), fila, 4);
                    
                    fila++;
                }
            }catch(SQLException e){}
            
        }
        tabla.setModel(modelo);
        /*int kms=0;
        for(int i=0;i<modelo.getRowCount();i++){
            kms=Integer.parseInt((String)modelo.getValueAt(i, 3));
        }
        labelkms.setText(kms+"");*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboconductor = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        areafecha1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        areafecha2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        areanif = new javax.swing.JTextField();
        areadireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        consultar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboconductor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboconductorItemStateChanged(evt);
            }
        });
        getContentPane().add(comboconductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 160, -1));

        jLabel1.setText("Conductor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel3.setText("desde fecha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        getContentPane().add(areafecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 70, -1));

        jLabel2.setText("hasta fecha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));
        getContentPane().add(areafecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 60, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("n.i.f.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(areanif, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 140, -1));
        jPanel1.add(areadireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 140, -1));

        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 240, 100));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 370, 90));

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboconductorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboconductorItemStateChanged
        // TODO add your handling code here:
        establecerDatos();
        for(int i=0;i<modelo.getRowCount();i++)
        modelo.removeRow(i);
    }//GEN-LAST:event_comboconductorItemStateChanged

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        
        obtenerResultados();
    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Camiones2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Camiones2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Camiones2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Camiones2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Camiones2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areadireccion;
    private javax.swing.JTextField areafecha1;
    private javax.swing.JTextField areafecha2;
    private javax.swing.JTextField areanif;
    private javax.swing.JComboBox comboconductor;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salir;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
